set -g mode-keys vi # I like vim motions

# Set prefix to CTRL-a
unbind C-b
set -g prefix C-a
bind -n C-a send-prefix

set -g default-terminal "tmux-256color"

# My preferences
set -g base-index 1          # Start indexing windows at 1 instead of 0
set -g renumber-windows on   # Renumber all windows when any window is closed
set -g status-position top   # macOS / darwin style
set -g allow-passthrough on  # Allow visible panes to bypass tmux
set -g status-left-length 150
set -g status-justify absolute-centre

# Nice plugins here
set -g @plugin 'catppuccin/tmux#v2.1.3'                 # Beautiful and customizable theme
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name' # Icons in windows
set -g @plugin 'tmux-plugins/tmux-sensible'             # Community-driven common settings
set -g @plugin 'tmux-plugins/tmux-pain-control'         # Pane controlling bindings
set -g @plugin 'tmux-plugins/tmux-resurrect'            # Restore tmux environment after system restart.
set -g @plugin 'tmux-plugins/tmux-continuum'            # Automatic restoring tmux sessions after reboot.
set -g @plugin 'tmux-plugins/tmux-sessionist'           # Easy manipulating sessions
set -g @plugin 'tmux-plugins/tpm'                       # Managing plugins

# Set up plugins
set -g @continuum-boot 'on'               # Start tmux server upon login
set -g @continuum-restore 'on'            # Restore last saved environment
set -g @resurrect-strategy-nvim 'session' # Start where we left off

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"

# To have status icons for windows, e.g. Focused, previous. none or text otherwise
set -g @catppuccin_window_flags "icon"

set -g status-right ""                               # Extra info only distracts you
set -g @catppuccin_window_flags_icon_current ""      # Color already gives you a hint
set -g status-left "#{E:@catppuccin_status_session}" # Status and session name on the left
set -ag @catppuccin_status_right_separator ""       # Still do not work, will fix later
set -g @catppuccin_window_text " #W"                 # Otherwise only hostname will be shown
set -g @catppuccin_window_current_text " #W"         # Otherwise only hostname will be shown

# Make tpm aware of non-usual plugins install dir
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'

# Tidying up config a little
if "test ! -d ~/.local/share/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"

run '~/.local/share/tmux/plugins/tpm/tpm'

# When just cloned to new machine run CTRL-a+I to install plugins
